services:
  iwanted:
    build: .
    container_name: iwanted_app
    ports:
      - "5500:3000" # http://localhost:5500
    volumes:
      - ./backend/data:/app/backend/data      # banco + uploads
      - ./frontend/public:/app/frontend/public # site est√°tico
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - ADMIN_USER=seu-usuario
      - ADMIN_PASS=sua-senha-segura
      - PUBLIC_URL=https://site.iwanted.shop
      - SUPABASE_URL=https://ozulqzzgmglucoaqhlen.supabase.co
      - SUPABASE_SERVICE_ROLE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dWxxenpnbWdsdWNvYXFobGVuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDEyOTc5OSwiZXhwIjoyMDc1NzA1Nzk5fQ.Pu9RLn2R5nOuBV6202xdnpWJ_8rE8coMmTiPHQewKK8
      - SUPABASE_TABLE=products_sheet
      - SUPABASE_VISITORS_TABLE=contador
